<?php

namespace CoolSpots\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CsCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CsCategoryRepository extends EntityRepository
{
}
