<?php

namespace CoolSpots\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CsGeoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CsGeoRepository extends EntityRepository
{
}
