main:
    pattern:    /
    defaults: { _controller: SiteBundle:Default:index }
  
locale:
    pattern:   /locale/{lang}
    defaults:  { _controller: SiteBundle:Default:locale, lang: en_US }
    requirements:
        lang: en_US|pt_BR
  
photo_show:
    pattern:  /{idLocation}/{slug}/{page}
    defaults: { _controller: SiteBundle:Photo:show, page: 1 }
    requirements:
        _method:  GET
        idLocation: \d+
        page: \d+

#### JSON routings ####
json_location:
    pattern: /json/location
    defaults: { _controller: SiteBundle:JSON:location }
    
json_location_info:
    pattern: /json/location/{id}/{slug}
    defaults: { _controller: SiteBundle:JSON:locationInfo }

json_photos:
    pattern: /json/photos/{idLocation}/{slug}
    defaults: { _controller: SiteBundle:JSON:photos }
        
about:
    pattern: /about
    defaults: { _controller: SiteBundle:About:index }

explore:
    pattern: /explore
    defaults: { _controller: SiteBundle:Explore:index }

favorites:
    pattern: /favorites
    defaults: { _controller: SiteBundle:Favorites:index }

messages:
    pattern: /messages
    defaults: { _controller: SiteBundle:Messages:index }

home:
    pattern: /home
    defaults: { _controller: SiteBundle:Home:index }
