main:
  pattern:    /
  defaults: { _controller: SiteBundle:Default:index }
  
locale:
  pattern:   /locale/{lang}
  defaults:  { _controller: SiteBundle:Default:locale, lang: en_US }
  requirements:
    lang: en_US|pt_BR
  
api_location:
    pattern: /json/location
    defaults: { _controller: SiteBundle:JSON:location }
