parameters:
#    site.example.class: CoolSpots\SiteBundle\Example

services:
    site.twig.site_extension:
        class: CoolSpots\SiteBundle\Twig\SiteExtension
        tags:
            - { name: twig.extension }