instagram_subscription:
    pattern:    /instagram/subscription/{object}/{object_id}
    defaults: { _controller: ApiBundle:Default:subscription }
    requirements:
        _method:  GET
        object_id: \d+

instagram_callback:
    pattern:    /instagram/callback
    defaults: { _controller: ApiBundle:Default:callback }

#instagram_callback:
#    pattern:    /instagram/callback/{object}/{object_id}
#    defaults: { _controller: ApiBundle:Default:callback }
#    requirements:
#        _method:  GET
#        object_id: \d+

json_location:
    pattern: /json/location
    defaults: { _controller: ApiBundle:JSON:location }
    requirements:
        _method: POST
        
json_location_info:
    pattern: /json/locationinfo
    defaults: { _controller: ApiBundle:JSON:locationInfo }
    requirements:
        _method: POST
        
json_photos:
    pattern: /json/photos
    defaults: { _controller: ApiBundle:JSON:photos }
    requirements:
        _method: POST
        
json_addlocation:
    pattern: /json/addlocation
    defaults: { _controller: ApiBundle:JSON:addLocation }
    requirements:
        _method: POST