instagram_subscription:
    pattern:    /instagram/subscription/{object}/{object_id}
    defaults: { _controller: ApiBundle:Default:subscription }
    requirements:
        _method:  GET
        object_id: \d+

instagram_callback:
    pattern:    /instagram/callback
    defaults: { _controller: ApiBundle:Default:callback }

json_location:
    pattern: /json/location
    defaults: { _controller: ApiBundle:JSON:location }
    requirements:
        _method: POST
        
json_location_info:
    pattern: /json/locationinfo
    defaults: { _controller: ApiBundle:JSON:locationInfo }
    requirements:
        _method: POST
        
json_photos:
    pattern: /json/photos
    defaults: { _controller: ApiBundle:JSON:photos }
    requirements:
        _method: POST
        
json_addlocation:
    pattern: /json/addlocation
    defaults: { _controller: ApiBundle:JSON:addLocation }
    requirements:
        _method: POST
        
json_favorites:
    pattern: /json/favorites
    defaults: { _controller: ApiBundle:JSON:favorites }
    requirements:
        _method: POST
        
json_addfavorites:
    pattern: /json/addfavorites
    defaults: { _controller: ApiBundle:JSON:addFavorites }
    requirements:
        _method: POST
        
json_removefavorites:
    pattern: /json/removefavorites
    defaults: { _controller: ApiBundle:JSON:removeFavorites }
    requirements:
        _method: POST
        
json_addevent:
    pattern: /json/addevent
    defaults: { _controller: ApiBundle:JSON:addEvent }
    requirements:
        _method: POST

json_adduser: 
    pattern: /json/adduser
    defaults: { _controller: ApiBundle:JSON:addUser }
    requirements:
        _method: POST