instagram_subscription:
    pattern:    /instagram/subscription/{object}/{object_id}
    defaults: { _controller: ApiBundle:Default:subscription }
    requirements:
        _method:  GET
        object_id: \d+

instagram_callback:
    pattern:    /instagram/callback
    defaults: { _controller: ApiBundle:Default:callback }

#instagram_callback:
#    pattern:    /instagram/callback/{object}/{object_id}
#    defaults: { _controller: ApiBundle:Default:callback }
#    requirements:
#        _method:  GET
#        object_id: \d+

json_location:
    pattern: /json/location
    defaults: { _controller: ApiBundle:JSON:location }
    
json_location_info:
    pattern: /json/location/{id}/{slug}
    defaults: { _controller: ApiBundle:JSON:locationInfo }

json_photos:
    pattern: /json/photos/{idLocation}/{slug}
    defaults: { _controller: ApiBundle:JSON:photos }
        
json_getgeo:
    pattern: /json/getgeo/{countryName}/{countryCode}/{stateName}/{stateAbbr}/{cityName}
    defaults: { _controller: ApiBundle:JSON:getGeo }

json_addlocation:
    pattern: /json/addlocation
    defaults: { _controller: ApiBundle:JSON:addLocation }
    requirements:
        _method: POST