instagram_subscription:
    pattern:    /instagram/subscription/{object}/{object_id}
    defaults: { _controller: ApiBundle:Default:subscription }
    requirements:
        _method:  GET
        object_id: \d+

instagram_callback:
    pattern:    /instagram/callback
    defaults: { _controller: ApiBundle:Default:callback }

json_locations:
    pattern: /json/locations
    defaults: { _controller: ApiBundle:JSON:locations }
    requirements:
        _method: POST
        
json_locations_info:
    pattern: /json/locations/info
    defaults: { _controller: ApiBundle:JSON:locationsInfo }
    requirements:
        _method: POST
        
json_locations_photos:
    pattern: /json/locations/photos
    defaults: { _controller: ApiBundle:JSON:locationPhotos }
    requirements:
        _method: POST
        
json_locations_add:
    pattern: /json/locations/add
    defaults: { _controller: ApiBundle:JSON:locationsAdd }
    requirements:
        _method: POST
        
json_favorites:
    pattern: /json/favorites
    defaults: { _controller: ApiBundle:JSON:favorites }
    requirements:
        _method: POST
        
json_favorites_add:
    pattern: /json/favorites/add
    defaults: { _controller: ApiBundle:JSON:favoritesAdd }
    requirements:
        _method: POST
        
json_favorites_remove:
    pattern: /json/favorites/remove
    defaults: { _controller: ApiBundle:JSON:favoritesRemove }
    requirements:
        _method: POST
        
json_events:
    pattern: /json/events
    defaults: { _controller: ApiBundle:JSON:events }
    requirements:
        _method: POST

json_events_add:
    pattern: /json/events/add
    defaults: { _controller: ApiBundle:JSON:eventsAdd }
    requirements:
        _method: POST

json_events_private:
    pattern: /json/events/private
    defaults: { _controller: ApiBundle:JSON:eventsPrivate }
    requirements:
        _method: POST

json_events_private_search:
    pattern: /json/events/private/search
    defaults: { _controller: ApiBundle:JSON:eventsPrivateSearch }
    requirements:
        _method: POST

json_events_self:
    pattern: /json/events/self
    defaults: { _controller: ApiBundle:JSON:eventsSelf }
    requirements:
        _method: POST

json_events_search:
    pattern: /json/events/search
    defaults: { _controller: ApiBundle:JSON:eventsSearch }
    requirements:
        _method: POST

json_users_add: 
    pattern: /json/users/add
    defaults: { _controller: ApiBundle:JSON:usersAdd }
    requirements:
        _method: POST

json_friends: 
    pattern: /json/friends
    defaults: { _controller: ApiBundle:JSON:friends }
    requirements:
        _method: POST
        
json_friend_request: 
    pattern: /json/friends/request
    defaults: { _controller: ApiBundle:JSON:friendsRequest }
    requirements:
        _method: POST
        
json_friends_request_status:
    pattern: /json/friends/request/status
    defaults: { _controller: ApiBundle:JSON:friendsRequestStatus }
    requirements:
        _method: POST
